url:"https://github.com/selimreza4136/mdselimreza.github.io"
baseurl: "/mdselimreza.github.io"
title: Md Selim Reza
logo: "/assets/images/formal.jpg"
description: Data Analyst/GRE Instructor
show_downloads: true
theme: jekyll-theme-minimal
